name: SonarCloud + Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # 1. Setup Python for unit tests
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    # 2. Install dependencies
    - name: Install coverage
      run: pip install coverage

    # 3. Run unit tests & create coverage.xml
    - name: Run tests with coverage
      run: |
        coverage run -m unittest discover
        coverage xml -o coverage.xml

    # 4. SonarCloud Scan
    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@8163df79c03e0a3e45c4c0cb9c1a5daeb4d9f81a

      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=manikandan1415_Devops-2.0
          -Dsonar.organization=manikandan1514
          -Dsonar.python.coverage.reportPaths=coverage.xml
